export const MOCK_PLAYER_DATA = {
    player: {
        player_id: '722478c1-69fe-4f55-8dee-55a3018b874d',
        first_name: 'Нұрасыл',
        last_name: 'Шиналиев',
        jersey_number: 78,
        team_id: 99,
        team_name: 'Ордабасы',
        position: 'Шабуылшы',
        date_of_birth: '2008-05-18',
        age: 17,
        height: 183,
        weight: 71,
        nationality: 'Қазақстан',
        is_homegrown: true,
        photo_url: 'http://localhost:9000/qfl-files/player_photos/722478c1-69fe-4f55-8dee-55a3018b874d.webp',
    },
    stats: {
        games_played: 10,
        minutes_played: 207,
        started: 2,
        subbed_in: 8,

        // Detailed stats matched to reference
        goals: 0,
        assists: 0,
        shots: 2,
        shots_on_goal: 0,
        passes: 49,
        key_passes: 25,
        pass_accuracy: 51,
        interception: 4,
        dribble: 5,

        yellow_cards: 0,
        red_cards: 0,
        duels: 70,
        duels_won: 31,
        duels_won_percentage: 44,
    },
    matches: [
        { round: 22, home: 'Шахтёр', away: 'Ордабасы', score: '1-1', date: '25 қазан 2025', minutes: 4 },
        { round: 20, home: 'Ертіс', away: 'Ордабасы', score: '1-2', date: '04 қазан 2025', minutes: 33 },
        { round: 19, home: 'Ордабасы', away: 'Каспий', score: '3-0', date: '27 қыркүйек 2025', minutes: 68 },
        { round: 18, home: 'Қайрат', away: 'Ордабасы', score: '2-0', date: '20 қыркүйек 2025', minutes: 16 },
        { round: 17, home: 'Ордабасы', away: 'Тараз', score: '4-1', date: '13 қыркүйек 2025', minutes: 1 },
        { round: 13, home: 'Жас Қыран', away: 'Ордабасы', score: '4-0', date: '02 тамыз 2025', minutes: 10 },
        { round: 6, home: 'Тараз', away: 'Ордабасы', score: '1-0', date: '25 мамыр 2025', minutes: 11 },
        { round: 5, home: 'Ордабасы', away: 'Ақтөбе', score: '3-2', date: '18 мамыр 2025', minutes: 3 },
        { round: 3, home: 'Ордабасы', away: 'Жас Қыран', score: '2-2', date: '04 мамыр 2025', minutes: 46 },
        { round: 2, home: 'Қайсар', away: 'Ордабасы', score: '1-2', date: '27 сәуір 2025', minutes: 15 },
    ],
    tournaments: [
        { id: 1, season: '2024', name: 'Freedom QJ League u17 (A)', team: 'Шаб', matches: 21, minutes: 1181, goals: 7, assists: 3, yellow: 10, red: 19 },
        { id: 2, season: '2025', name: 'Freedom QJ League', team: 'Шаб', matches: 10, minutes: 207, goals: 0, assists: 0, yellow: 0, red: 2 },
    ],
    teammates: [
        // Adding placeholder images or leaving null if no mock images available
        { player_id: 'tm1', jersey_number: 70, first_name: 'Құдірет', last_name: 'Ботабек', position: 'Шабуылшы', age: 17, photo_url: 'https://via.placeholder.com/200x280?text=70' },
        { player_id: 'tm2', jersey_number: 18, first_name: 'Асхат', last_name: 'Жаңбырбай', position: 'Шабуылшы', age: 17, photo_url: 'https://via.placeholder.com/200x280?text=18' },
        { player_id: 'tm3', jersey_number: 17, first_name: 'Жанәлі', last_name: 'Есеналиев', position: 'Шабуылшы', age: 18, photo_url: 'https://via.placeholder.com/200x280?text=17' },
        { player_id: 'tm4', jersey_number: 10, first_name: 'Аслан', last_name: 'Кенжебек', position: 'Жартылай қорғаушы', age: 18, photo_url: 'https://via.placeholder.com/200x280?text=10' },
        { player_id: 'tm5', jersey_number: 5, first_name: 'Дәурен', last_name: 'Тұрсынов', position: 'Қорғаушы', age: 17, photo_url: 'https://via.placeholder.com/200x280?text=5' },
        { player_id: 'tm6', jersey_number: 1, first_name: 'Бекнұр', last_name: 'Исмаилов', position: 'Қақпашы', age: 18, photo_url: 'https://via.placeholder.com/200x280?text=1' },
    ]
};
